name: my_invoice_app
description: An offline Flutter invoice app with thermal Bluetooth printing and ZATCA e-invoicing integration.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path_provider: ^2.0.14
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.11.1
  qr_flutter: ^4.0.0
  flutter_blue_plus: ^1.10.0
  shared_preferences: ^2.2.2
  image_picker: ^0.8.9
  google_fonts: ^4.0.3
  permission_handler: ^12.0.0+1
  path: ^1.8.3
  esc_pos_utils_plus: ^2.0.4
  image: ^4.0.17
  flutter_widget_to_image: ^0.0.1
  screenshot: ^3.0.0
  render_metrics: ^2.0.2
  pdfx: ^2.9.2
  archive: ^3.4.9
  # Supabase dependencies
  supabase_flutter: ^2.3.4
  http: ^1.1.0
  crypto: ^3.0.3
  # Additional dependencies for ZATCA integration
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/qr_fallback.png
    - assets/logo.png
    - assets/fonts/NotoNaskhArabic-Regular.ttf
    - assets/fonts/NotoNaskhArabic-Bold.ttf
    - assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - assets/fonts/NotoNaskhArabic-SemiBold.ttf
    - assets/fonts/NotoNaskhArabic-Medium.ttf
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
    - assets/fonts/NotoSansArabic-Bold.ttf
    - assets/fonts/NotoSansArabic-Regular.ttf
    - assets/fonts/Amiri-Bold.ttf
    - assets/fonts/Amiri-Regular.ttf